<?php

namespace handler;

interface HandlerInterface {
    /**
     * Read contents from source
     * @param string $source
     */
    public function read(string $source);

    /**
     * Write content to source
     * 
     */
    public function write(string $source, $content);

    /**
     * Write content to temp PHP file, and returns content
     * 
     * @param $content Data to write
     * @return Stream content formated
     */
    public function toStream($content);

    /**
     * Retrieve de content type of data
     *
     * @return string Type of content generated by this class
     */
    public function getContentType();
}
